config/routes.rb
Rails.application.routes.draw do
  devise_for :players, controllers: { registrations: 'registrations' }
  resources :games, only: [:index] do
    resources :join_games, only: :create
  end
  resource :dashboard, :only => [:show]
  root 'static_pages#index'
  resources :games
  resource :pieces, only: [:update]
  get 'about', :to => 'static_pages#about'
  get 'code', :to => 'static_pages#code'
  get 'game_over', :to => 'static_pages#game_over'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :pieces
  has_many :join_games
  has_many :joined_players, through: :join_games, source: :player
  belongs_to :players

  def in_check?(color)
    king = Piece.find_by(type: 'King', color: color, game_id: id )
    color == true ? enemy_color = false : enemy_color = true
    enemies = Piece.where(color: enemy_color , game_id: id)
    in_check = false

    enemies.each do |enemy|
      if enemy.legal_move?(king.x_position, king.y_position)
        @enemy_making_check = enemy
        in_check = true
      end
    end
    in_check
  end

  def moving_in_to_check?(x, y, color)
    king = Piece.find_by(type: 'King', color: color, game_id: id )
    color == true ? enemy_color = false : enemy_color = true
    enemies = Piece.where(color: enemy_color , game_id: id)
    in_check = false

    enemies.each do |enemy|
      if enemy.legal_move?(x, y)
        @enemy_making_check = enemy
        in_check = true
      end
    end
    in_check
  end

  def captured_pieces(x, y, board)
    self.dead_pieces << [board.board[y][x].type, board.board[y][x].color]
    self.save!
  end

  def in_checkmate?
    # Checks to see if either player is in checkmate.
  end

  def player_turn
    # Checks to see who's turn it is.
  end

  def check_two_players_present
    # Checks that two players are present(logged in) to play.
  end

  def legal_castle_move?(x, y, color, game_id)
    king = Piece.find_by(type: 'King', color: color, game_id: game_id)

    if king.color == false
      if king.x_position == 4
        if king.y_position == 0
          black_king = king
        else
          return false
        end
      else
        return false
      end
      if black_king.moved
        return false
      end
    else
      if king.x_position == 4
        if king.y_position == 7
          white_king = king
        else
          return false
        end
      else
        return false
      end
      if white_king.moved
        return false
      end
    end

    if (x - king.x_position).abs == 2
      if y != king.y_position
        return false
      end
    else
      return false
    end

    if x > king.x_position && king.color == false
      black_king_rook = Piece.find_by(x_position: 7, y_position: 0, type: 'Rook', color: color, game_id: game_id)
      if black_king_rook == nil
        return false
      elsif black_king_rook.moved
        return false
      else
        return true
      end
    elsif x > king.x_position && king.color == true
      white_king_rook = Piece.find_by(x_position: 7, y_position: 7, type: 'Rook', color: color, game_id: game_id)
      if white_king_rook == nil
        return false
      elsif white_king_rook.moved 
        return false
      else
        return true
      end
    elsif x < king.x_position && king.color == false
      black_queen_rook = Piece.find_by(x_position: 0, y_position: 0, type: 'Rook', color: color, game_id: game_id)
      if black_queen_rook == nil
        return false
      elsif black_queen_rook.moved 
        return false
      else
        return true
      end
    elsif x < king.x_position && king.color == true
      white_queen_rook = Piece.find_by(x_position: 0, y_position: 7, type: 'Rook', color: color, game_id: game_id)
      if white_queen_rook == nil
        return false
      elsif white_queen_rook.moved
        return false
      else
        return true
      end
    else
      return false
    end  
  end

  def castling_occured(x, y, color, game_id)
    king = Piece.find_by(type: 'King', color: color, game_id: game_id)
    
    if self.legal_castle_move?(x, y, color, game_id)
      castling = true
    else
      castling = false
    end

    if castling == true
      if x > king.x_position && king.color == false
        black_king_rook = Piece.find_by(x_position: 7, y_position: 0, type: 'Rook', color: color, game_id: game_id)
        black_king_rook.update_attributes(x_position: 5, moved: true)
      elsif x > king.x_position && king.color == true
        white_king_rook = Piece.find_by(x_position: 7, y_position: 7, type: 'Rook', color: color, game_id: game_id)
        white_king_rook.update_attributes(x_position: 5, moved: true)
      elsif x < king.x_position && king.color == false
        black_queen_rook = Piece.find_by(x_position: 0, y_position: 0, type: 'Rook', color: color, game_id: game_id)
        black_queen_rook.update_attributes(x_position: 2, moved: true)
      elsif x < king.x_position && king.color == true
        white_queen_rook = Piece.find_by(x_position: 0, y_position: 7, type: 'Rook', color: color, game_id: game_id)
        white_queen_rook.update_attributes(x_position: 2, moved: true)
      end
    else
      return false
  end  

  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  respond_to :js, :json, :html
  before_action :authenticate_player!, only: [:new, :create]

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    @pieces = Piece.where(game_id: @game.id)
    unless @game.player_two_id == nil
      @player_one = Player.find(@game.player_one_id)
      @player_two = Player.find(@game.player_two_id)
    end
    @board = Board.new
    @board.refresh(@game.id)
  end

  def new
    @game = Game.new
  end

  def update
    @game = Game.find(params[:id])
    @new_piece = (params[:type])
    promotion_piece = Piece.where(y_position: 7, type: 'Pawn', color: false).first
    if promotion_piece == nil
      promotion_piece = Piece.where(y_position: 0, type: 'Pawn', color: true).first
    end
    unless promotion_piece == nil
    @player = Player.find(promotion_piece.player_id)
    Piece.create(type: @new_piece, x_position: promotion_piece.x_position, y_position: promotion_piece.y_position, color: promotion_piece.color, player_id: @player.id, game_id: @game.id)
    promotion_piece.destroy

    redirect_to game_path(@game.id)
    else
      flash[:warning] = 'You are not eligible for a pawn promotion'

      redirect_to game_path(@game.id)
    end
  end

  def create
    @game = current_player.games.create(game_params)
    current_player.join_games.create(game: @game)
    @game.update_attributes(player_one_id: current_player.id, turn: current_player.id)
    redirect_to game_path(@game)
  end


  private

  def game_params
    params.require(:game).permit(:name)
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_gameboard.html.erb
<div id = 'gameContainer' class = 'col-xs-12'>
  <div id = 'deadPieceContainer'>
    <table id = 'deadPieces'>
      <tr>
	<%= @board.dead_table(@game, 'f') %>
      </tr>
    </table>
  </div>

  <div id = 'gameboardContainer'>
    <table id= "gameboard", class = "chess-board">

      <% @board.board.each_with_index do |row, y| %>
	<tr>
	  <% @board.board.reverse.each_with_index do |column, x| %>
	    <%= @board.pieces(y, x, @game) %>
	  <% end %>
	</tr>
      <% end %>

    </table>
  </div>

  <div id = 'deadPieceContainer2'>
    <table id = 'deadPieces2'>
      <tr>
	<%= @board.dead_table(@game, 't') %>
      </tr>
    </table>
  </div>

</div>

app/views/games/index.html.erb
<div class="container-responsive col-xs-12 col-md-6 col-md-offset-3">
  <section class="my-games">

    <h1 class="text-center display-4 hidden-sm-down">Open Games</h1>
    <h2 class = 'text-center hidden-md-up'>Open Games</h2>
    <% @games.where(player_two_id: nil).each do |game| %>
      <div class="game-list-item">
        <ul class="list-unstyled">
          <li class="text-center"><h3><%= link_to game.name, game_path(game), id: 'gameName' %></h3></li>
          <% player1 = Player.find(game.player_one_id) %>
          <% case player1.first_name.nil? %>
            <% when true %>
              <li class="text-center"><h4>
                <%= player1.email + " vs " %>&nbsp;<%= link_to "Join Game", game_join_games_path(game.id), class: 'btn btn-sm btn-default', method: :post %></h4>
              </li>
            <% when false %>
              <li class ="text-center"><h4><%= player1.first_name + " vs " %>&nbsp;<%= link_to "Join Game", game_join_games_path(game.id), class: 'btn btn-success-outline', method: :post %></h4>
              </li>
            <% end %>
        </ul>
      </div>
    <% end %>
      
  <div class="clear"></div>

    <h1 class="text-center display-4 hidden-sm-down">Current Games</h1>
    <h2 class = 'text-center hidden-md-up'>Current Games</h2>
    <% @games.each do |game| %>
      <% if game.player_two_id != nil %>
        <div class="game-list-item">
          <ul class="list-unstyled">
            <li class="text-center">
              <h3><%= link_to game.name, game_path(game), id: 'gameName' %></h3>
            </li>
            <% player1, player2 = Player.find(game.player_one_id), Player.find(game.player_two_id) %>
            <% case [player1.first_name.nil?, player2.first_name.nil?] %>
              <% when [true, true] %>
                <li class="text-center"><h4><%= player1.email + " vs ".html_safe + player2.email %></h4></li>
              <% when [true, false] %>
                <li class="text-center"><h4><%= player1.email + " vs " + player2.first_name %></h4></li>
              <% when [false, true] %>
                <li class="text-center"><h4><%= player1.first_name + " vs ".html_safe + player2.email %></h4></li>
              <% when [false, false] %>
                <li class="text-center"><h4><%= player1.first_name + " vs ".html_safe + player2.first_name %></h4></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>
  </section>
</div>

app/views/games/new.html.erb
<div class = 'container-responsive'>
  <div class = 'col-xs-12 col-md-6 col-md-offset-3'>
    <div id = 'startGame' class="game-list-item text-center ">
      <h1>Start a Game</h1>
      <%= simple_form_for @game, :url => games_path do |f| %>
	<br />
	<%= f.input :name, label: false, placeholder: 'Game Name' %>
	<br />
	<%= f.submit "Create", :class => 'btn btn-primary pull-right' %>
	<br />
      <% end %>
      <br />
    </div>
  </div>
</div>

app/views/games/show.html.erb
<br />
<div class="container-responsive">
  <section class="my-games">
  <h1 class="text-center"><%= @game.name %></h1>

  <div class = 'col-xs-12'>
    <% flash.each do |key, value| %>
      <div class = 'col-md-4 hidden-sm-down'></div>
      <div class="alert alert-info col-xs-12 col-md-4"><%= value %></div>
      <div class = 'col-md-4 hidden-sm-down'></div>
    <% end %>
  </div>

  <div class = 'col-xs-12'>
    <% unless @game.player_two_id == nil %>
      <h3 class = 'text-center name'>Player Two: <%= @player_two.first_name %>
	<% if @game.turn == @game.player_two_id %>
	  <div class = 'attention'>
	    <span class = 'mega-octicon octicon-chevron-left'></span><small> Player Two's turn!</small>
	  </div>
	<% end %>
      </h3>
    <% end %>
  </div>

  <%= render "gameboard" %>

  <div class = 'col-xs-12'>
    <% unless @game.player_two_id == nil %>
      <h3 class = 'text-center name'>Player One: <%= @player_one.first_name %>  
	<% if @game.turn == @game.player_one_id %>
	  <div class = 'attention'>
	    <span class = 'mega-octicon octicon-chevron-left'></span><small> Player One's turn!</small>
	  </div>
	<% end %>
      </h3>
    <% end %>
  </div>

  </section>
  <!-- Modal -->
  <div class="modal fade" id="pawnPromotion" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
	<div class="modal-header">
	  <h4 class="modal-title" id="myModalLabel">Pawn Promotion!</h4>
	</div>
	<div class="modal-body">
	  <h5>
	    Select the piece you would like to replace your pawn.
	  </h5>
	  <% unless current_player == nil %>
	    <% @color = nil %>
	    <% if current_player.id == @game.player_two_id %>
	      <% @color = 'black' %>
	    <% else %>
	      <% @color = 'white' %>
	    <% end %>
	    <%= link_to image_tag("#{@color}_queen.png"), game_path(@game, type: 'Queen'), data: {confirm: 'Are you sure you want the Queen?'}, method: :put %>
	    <%= link_to image_tag("#{@color}_knight.png"), game_path(@game, type: 'Knight'), data: {confirm: 'Are you sure you want the Knight?'}, method: :put %>
	    <%= link_to image_tag("#{@color}_bishop.png"), game_path(@game, type: 'Bishop'), data: {confirm: 'Are you sure you want the Bishop?'}, method: :put %>
	    <%= link_to image_tag("#{@color}_rook.png"), game_path(@game, type: 'Rook'), data: {confirm: 'Are you sure you want the Rook?'}, method: :put %>
	  <% end %>
	</div>
      </div>
    </div>
  </div>
  <script>
    $(document).ready(function() {
      var board = $('#gameboard');
      var deadPieces = $('#deadPieceContainer');
      var deadPieces2 = $('#deadPieceContainer2');

      var calculateLeft = function(board, deadPieces) {
	var screen = $(document).width() / 2;
	var boardWidth = board.width() / 2;
	var deadWidth = deadPieces.width();
	return screen - boardWidth - deadWidth - 5;
      }

      var calculateRight = function (board) {
	var screen = $(document).width() / 2;
	var boardWidth = board.width() / 2;
	return screen + boardWidth + 1;
      }
      deadPieces.css({'left':calculateLeft(board, deadPieces),'display':'initial'});
      deadPieces2.css({'left':calculateRight(board),'display':'initial'});

      $(window).on('resize', function() {
	deadPieces.css('left', calculateLeft(board, deadPieces));
	deadPieces2.css('left', calculateRight(board));
      });

      if(window.location.hash == "#pawnPromotion") {
	$('#pawnPromotion').modal({
	  keyboard: false,
	  backdrop: 'static'
	});
      }

      $('#gameboard td').click(function() {
	$this = $(this);
	var pieceIsSelected = $('#gameboard td').hasClass('selected');
	if (pieceIsSelected){
	  var $piece = selectedPiece();
	  if ($piece.data('piece-id') == $this.data('piece-id')) {
	    deselectPiece( $this );
	    } else {
	    sendMove( $this );
	  }
	  } else {
	  selectPiece($this);
	}
	function selectedPiece() {
	  return $('#gameboard td.selected');
	}
	function selectPiece($piece) {
	  $piece.addClass('selected');
	}
	function deselectPiece($piece) {
	  $piece.removeClass('selected');
	}
	function sendMove($new_space) {
	  $this = $new_space
	  var $x = $this.data('x');
	  var $y = $this.data('y');
	  var $pieceId = $piece.data('piece-id');
	  jQuery.ajax({
	    url: "<%= pieces_path %>",
	    type: "PATCH",
	    data: {new_x: $x, new_y: $y, pieceId: $pieceId},
	    success: function(data) {
	      $(location).attr('href', data.update_url);
	      $(document).ajaxStop(function() { 
		location.reload(true); 
	      });
	    }
	  });
	}
      });
    });
  </script>
</div>