config/routes.rb
Rails.application.routes.draw do
  devise_for :players, controllers: { registrations: 'registrations' }
  resources :games, only: [:index] do
    resources :join_games, only: :create
  end
  resource :dashboard, :only => [:show]
  root 'static_pages#index'
  resources :games
  resource :pieces, only: [:update]
  get 'about', :to => 'static_pages#about'
  get 'code', :to => 'static_pages#code'
  get 'game_over', :to => 'static_pages#game_over'

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	# before_action :authenticate_player! 

	def show
		
	end

end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/show.html.erb
<br />

<div class="my-games">
  <section class="container-responsive text-center col-xs-12 col-md-6 col-md-offset-3">
  <h1 class = 'display-4 hidden-sm-down'>My Games</h1>
  <h2 class = 'hidden-md-up'>My Games</h2>
  <% current_player.joined_games.each do |game| %>
    <% if game.player_two_id != nil %>
      <div class="game-list-item">
	<ul class="list-unstyled text-center">
	  <li><h3><%= link_to game.name, game_path(game), id: 'gameName' %></h3></li>
	  <% player1, player2 = Player.find(game.player_one_id), Player.find(game.player_two_id) %>
	  <% case [player1.first_name.nil?, player2.first_name.nil?] %>
	  <% when [true, true] %>
	    <li><h4><%= player1.email + " vs " + player2.email %></h4></li>
	  <% when [true, false] %>
	    <li><h4><%= player1.email + " vs " + player2.first_name %></h4></li>
	  <% when [false, true] %>
	    <li><h4><%= player1.first_name + " vs " + player2.email %></h4></li>
	  <% when [false, false] %>
	    <li><h4><%= player1.first_name + " vs " + player2.first_name %></h4></li>
	  <% end %>
	</ul>
      </div>    	
    <% end %>
  <% end %>
  <div class = 'clear' ></div>

  <h1 class = 'hidden-sm-down display-4'>My Open Games</h1>
  <h2 class = 'hidden-md-up'>My Open Games</h2>
  <% current_player.joined_games.each do |game| %>
    <% if game.player_two_id == nil %>
      <% player1 = Player.find(game.player_one_id) %>
      <div class = "game-list-item"> 
	<ul class = "list-unstyled text-center">
	  <li><h3><%= link_to game.name, game_path(game), id: 'gameName' %></h3><li>
	  <% case player1.first_name.nil? %>
	  <% when true %>
	    <li><h3><%= player1.email + " vs " %><% link_to "Join Game", game_join_games_path(game.id), class: 'btn btn-secondary-outline', method: :post %><h3></li>
	  <% when false %>
	    <li><h3><%= player1.first_name + " vs " %><%= link_to "Join Game", game_join_games_path(game.id), class: 'btn btn-secondary-outline', method: :post %><h3></li>
	  <% end %>
	</ul>
      </div>
    <% end %>
  <% end %>
  <br class = "clear"></div>
  </section>
</div>