config/routes.rb
Rails.application.routes.draw do
  devise_for :players, controllers: { registrations: 'registrations' }
  resources :games, only: [:index] do
    resources :join_games, only: :create
  end
  resource :dashboard, :only => [:show]
  root 'static_pages#index'
  resources :games
  resource :pieces, only: [:update]
  get 'about', :to => 'static_pages#about'
  get 'code', :to => 'static_pages#code'
  get 'game_over', :to => 'static_pages#game_over'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Team Whip Chess</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class = 'container-responsive'>
      <nav class="navbar navbar-static-top">
	<button type="button" id= 'toggle-nav' class="navbar-toggler hidden-sm-up rotate-down mega-octicon octicon-chevron-down" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
	  <span class="sr-only">Toggle navigation</span>
	</button>
      <div class = 'collapse navbar-toggleable-xs' id = 'navbar-collapse-1'>
	<%= link_to 'Team Whip', root_path, class: "navbar-brand" %>
	<ul class="nav navbar-nav pull-left">
	  <li class="nav-item <%= 'active' if current_page?(new_game_path) %>"><%= link_to 'Start a Game', new_game_path, class: "nav-link" %></li>
	  <li class="nav-item <%= 'active' if current_page?(games_path) %>"><%= link_to 'Current Games', games_path, class: "nav-link" %></li>
	</ul>
	<ul class="nav navbar-nav pull-right">
	  <% if player_signed_in? %>
	    <% if current_player.first_name.present? %>
	      <li class = 'nav-item'><%= link_to "#{current_player.first_name}'s Dashboard", dashboard_path, class: "nav-link" %></li>
	    <% else %>
	      <li class = 'nav-item'><%= link_to "User Dashboard", dashboard_path, class: "nav-link" %></li>
	    <% end %>
	    <li class = 'nav-item'><%= link_to 'Sign out', destroy_player_session_path, method: :delete, class: "nav-link" %></li>
	  <% else %>
	    <li class = 'nav-item'><%= link_to 'Login', player_session_path, class: "nav-link" %></li>
	    <li class = 'nav-item'><%= link_to 'Sign Up', new_player_registration_path, class: "nav-link" %></li>
	  <% end %>
	</ul>
      </div>
      </nav>

      <%= yield %>

      <!-- footer -->
      <nav class="navbar navbar-fixed-bottom">
	  <ul class="navbar-nav nav pull-left">
	    <li class = "nav-item"><%= link_to 'About', about_path, class: 'nav-link' %></li>
	    <li class = "nav-item"><%= link_to 'Code', '#', class: 'nav-link' %></li>
	  </ul>
	  <div class="github-icon pull-right">
	    <a href = 'https://github.com/Team-whip/chess_app'><span class = 'mega-octicon octicon-mark-github'></span></a>
	  </div>
      </div>
    </nav>


    <script>
      $(document).ready(function() {
	$('#toggle-nav').click(function() {
	  $this = $(this);

	  if ($this.hasClass('rotate-up')) {
	    $this.removeClass('rotate-up');
	    $this.addClass('rotate-down');
	    } else {
	    $this.removeClass('rotate-down');
	    $this.addClass('rotate-up');
	    $('.masthead').addClass('masthead-collapse');
	  }
	});
      });
    </script>
  </body>
</html>